###############################################


###############################################
#Chance to drop a player head when defeated in pvp by another player
Player_PvP_Head: false

#Sets the % chance per kill to drop a head, if 100 or above always drop a head
Player_PvP_Head_DropChance: 100.0

#Adds x% per looting level on the killing weapon to drop a head
Player_PvP_Head_Looting_Modifier: 3.0
###############################################

###############################################
#Chance to drop heads from players landing the final blow on any living entity
Player_Kill_Entity_Head: false
#Sets the % chance per kill to drop a head, if 100 or above always drop a head
Player_Kill_Entity_Dropchance: 1.6
#Adds x% per looting level on the killing weapon to drop a head
Player_Kill_Entity_Looting_Modifier: 3
###############################################


###############################################
#Enables Head drops on creeper explosions does not need to be a killing blow
Creeper_Explosion_Head: true
#Creeper explosion needs to be a killing blow to drop a head
Creeper_Killing_Blow: false
#Only drop heads from Charged creeper damage
Charged_Creeper_Required: true
#Sets the % chance to drop a head on the above selected settings
Creeper_Head_Dropchance: 100.0
###############################################


###############################################
#Removes Vanilla Heads from dropping on charged creeper explosions,
#if set to false 2 heads drop from creepers, skeletons and zombies by default
Remove_Vanilla_Mob_Heads: true

#If set to false the head will still drop, above value must be set to true to take these
#settings into account
Remove_Vanilla_Zombie_Head: true
Remove_Vanilla_Creeper_Head: true
Remove_Vanilla_Skeleton_Head: true
