#Configs for Head plugin

#Enables Heads to drop in pvp
Player_PvP_Head: false

#DropChance for pvp kill head drops in %
Player_PvP_Head_DropChance: 100

#Enables Head drops from normal kills
Player_Kill_Entity_Head: false

#Dropchance per kill in %
Player_Kill_Entity_Dropchance: 0.0
#Looting modifier dropchance disabled if 0
Player_Kill_Entity_Looting_Modifier: 3


#Enables Head drops from Creeper explosions
Creeper_Explosion_Head: true

#Only drop heads from Charged creeper damage
Charged_Creeper_Required: true

#Default Head options
Remove_Vanilla_Mob_Heads: true

#Specific vanilla heads, only works if Remove_Vanilla_Mob_Heads is set to true
Remove_Vanilla_Zombie_Head: true
Remove_Vanilla_Creeper_Head: true
Remove_Vanilla_Skeleton_Head: true