name: Heads
version: '${project.version}'
main: com.wonkglorg.Heads
api-version: 1.19
authors: [ Wonkglorg ]
description: Customizable Head Plugin for dropping heads from mobs and players in various ways
commands:
  spawn-creeper:
    description: Spawns creeper at the clicked location
    usage: "Usage: /<command> <args>"
    permission: Heads.SpawnCreeper
    permission-message: You do not have permission to use this command!
  drop-heads:
    description: Drops head of specified type
    usage: "Usage: /<command> <args>"
    permission: Heads.DropHeads
    permission-message: You do not have permission to use this command!
  reload-heads:
    description: Reloads configs
    usage: "Usage: /<command> <args>"
    permission: Heads.Reload.Config
    permission-message: You do not have permission to use this command!
