name: WonkyHeads
version: '${project.version}'
main: com.wonkglorg.Heads
api-version: 1.19
authors: [ Wonkglorg ]
description: Customizable Head Plugin for dropping heads from mobs and players in various ways
softdepend: [ CrazyAdvancementsAPI ]
commands:
  spawn-creeper:
    description: Spawns creeper at the clicked location
    usage: "Usage: /<command> <args>"
    permission: Heads.spawnCreeper
    permission-message: You do not have permission to use this command!
  givemobhead:
    description: Drops head of specified type
    usage: "Usage: /<command> <args>"
    permission: Heads.give.head.mobHead
    permission-message: You do not have permission to use this command!
  givecustomhead:
    description: Drops custom head
    usage: "Usage: /<command> <args>"
    permission: Heads.give.head.custom
    permission-message: You do not have permission to use this command!
  head-config-reload:
    description: Reloads configs
    usage: "Usage: /<command> <args>"
    permission: Heads.reload.config
    permission-message: You do not have permission to use this command!
  headconfig:
    description: Opens gui for head config
    usage: "Usage: /<command>"
    permission: Heads.gui.config
    permission-message: You do not have permission to use this command!
  value:
    description: sets value for menu
    usage: "Usage: /<command>"
    permission: Heads.gui.value
    permission-message: You do not have permission to use this command!
  dropchance:
    description: tests dropchance of a path of heads
    usage: "Usage: /<command>"
    permission: Heads.dropchance.test
    permission-message: You do not have permission to use this command!